apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared
  namespace: jupyterhub
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard